### ISSUE TITLE
Service Architecture

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/ahb-decision-support-sdk#2]
So we are starting to add issues about services in this repo before we have designed the lay of the land for our repos.  I think this really comes down to one major question: Are we going to build true, standalone services that will be used by/and thought of, as their own living creature(s).  No strings attached to the decision support tool (even though the decision support tool will motivate most design decisions at first).

If the answer is YES.  Then I propose each services (to which the answer is yes), be made into it's own repo.  Issues logged there, code, data, tests handled there.

If the answer is NO.  Then I propose the farm-budgets-app/sdk structure.  Which can seem a little backward at first.  The structure breaks out like this:

App
- UI code (browser client)
- Backend Services (server)
- Depends on SDK

SDK
- Core business logic.
- Rest API wrappers. (so has an inherent dependency on the App server backend).
- standalone (assuming a app server is live and accessible on the network, you can use SDK from script, command line, 3rd party app)
- isomorphic (can always be compiled to run in browser).

You can think of it as:
Client UI (App Code) -> Core (SDK Code) -> Server (App Code)

@qjhart please let me know your thoughts and which direction you would like to take the 2/3 services required to be built for the decision support app.

Also, I think we might want to look at a new soil/weather service (wrapper?) as well.  The current per-ahb-pixel service is killing early demo performance, flooding the network with requests that should be one call.

**Comment by qjhart** [comment]
You didn't identify what you thought was better.  Personally, I think that that the services should go in the app, and not as separate projects.  Mostly because I don't think anyone else is likely to use them, outside of the support app.  The reason against that, is besides the services, I don't see what the server is, and if they were moved, then the -app would have not server requirements whatsoever.

**Comment by jrmerz** [comment]
I would say that I don't know a use case for these services outside this app... but that in no way means there isn't one that you are thinking of.  So I didn't say which I thought was better due to my ignorance on the topic.  Sounds like you want to move the services into to app code, which I am more than fine with.

As for if the two services weren't in the -app repo... 
- There is nothing that says the -app HAS to have a 'service' server.  The app can always just be served statically from apache.  Much like the current demo is now.
- And there can always arise a need for new service/end points.  Off the top of my head there will most likely be a storage/fetch mechanism in place for pre-cooked setups/case studies.

Anyway, sounds like we will plan on building the services inside the app repo.  Perhaps we should open tickets on tech stack(s) for these services in the -app repo.

**Comment by qjhart** [comment]
Sounds good.  I'll move the Transportation issue.
